# Generated by Django 4.1.5 on 2023-01-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.CharField(max_length=5)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1001)),
                ('idade', models.CharField(max_length=4)),
                ('sexo', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('relatorio_de_saude', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trocas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.CharField(max_length=10)),
                ('alimentos', models.CharField(max_length=30)),
                ('medicacao', models.CharField(max_length=30)),
                ('municao', models.CharField(max_length=30)),
                ('pontos_agua', models.CharField(max_length=10)),
                ('pontos_alimento', models.CharField(max_length=10)),
                ('pontos_medicacao', models.CharField(max_length=10)),
                ('pontos_municao', models.CharField(max_length=10)),
            ],
        ),
    ]
